// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiBackApi.Data;

namespace TaxiBackApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210327140539_KEkw")]
    partial class KEkw
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaxiBackApi.Models.ConvertedJsonOrder", b =>
                {
                    b.Property<int>("ConvertedJsonOrderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<int?>("productid")
                        .HasColumnType("int");

                    b.HasKey("ConvertedJsonOrderid");

                    b.HasIndex("RootId");

                    b.HasIndex("productid");

                    b.ToTable("ConvertedJsonOrder");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConvertedJsonOrderid")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("ConvertedJsonOrderid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("discountAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paidPrice")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("remoteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unitPrice")
                        .HasColumnType("int");

                    b.Property<string>("vatPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("RootId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Root", b =>
                {
                    b.Property<int>("RootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("orderNumber")
                        .HasColumnType("int");

                    b.HasKey("RootId");

                    b.ToTable("Root");
                });

            modelBuilder.Entity("TaxiBackApi.Models.ConvertedJsonOrder", b =>
                {
                    b.HasOne("TaxiBackApi.Models.Root", "root")
                        .WithMany()
                        .HasForeignKey("RootId");

                    b.HasOne("TaxiBackApi.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");

                    b.Navigation("product");

                    b.Navigation("root");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Order", b =>
                {
                    b.HasOne("TaxiBackApi.Models.ConvertedJsonOrder", "ConvertedJsonOrder")
                        .WithMany()
                        .HasForeignKey("ConvertedJsonOrderid");

                    b.Navigation("ConvertedJsonOrder");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Product", b =>
                {
                    b.HasOne("TaxiBackApi.Models.Root", null)
                        .WithMany("products")
                        .HasForeignKey("RootId");
                });

            modelBuilder.Entity("TaxiBackApi.Models.Root", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
